// Tailwind v4 로 styles.css 를 컴파일하고, 그 결과를 TS 문자열 모듈로 codegen 한다.
// 라이브러리 빌드(tsdown)가 CSS 를 문자열로 번들에 인라인하기 위함 — 호스트는 Tailwind 를 몰라도 된다.
import {execFileSync} from 'node:child_process';
import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {dirname, resolve} from 'node:path';
import {fileURLToPath} from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const tmp = resolve(root, '.tmp/styles.css');
mkdirSync(dirname(tmp), {recursive: true});

execFileSync('pnpm', ['exec', 'tailwindcss', '-i', 'src/styles.css', '-o', tmp, '--minify'], {
  cwd: root,
  stdio: 'inherit',
});

const css = readFileSync(tmp, 'utf8');
const out = resolve(root, 'src/generated/styles.ts');
mkdirSync(dirname(out), {recursive: true});
writeFileSync(out, `// AUTO-GENERATED by scripts/gen-css.mjs. Do not edit.\nexport default ${JSON.stringify(css)};\n`);
console.log(`✓ generated styles.ts (${css.length} bytes)`);
